//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 12:26:38 PM EAT 
//


package ke.co.kanji.kcb.customers;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ke.co.kanji.kcb.customers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ke.co.kanji.kcb.customers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ken21083KcbCustomerCreateRequest }
     * 
     */
    public Ken21083KcbCustomerCreateRequest createKen21083KcbCustomerCreateRequest() {
        return new Ken21083KcbCustomerCreateRequest();
    }

    /**
     * Create an instance of {@link Ken21083KcbCustomerCreateResponse }
     * 
     */
    public Ken21083KcbCustomerCreateResponse createKen21083KcbCustomerCreateResponse() {
        return new Ken21083KcbCustomerCreateResponse();
    }

    /**
     * Create an instance of {@link CreationStatus }
     * 
     */
    public CreationStatus createCreationStatus() {
        return new CreationStatus();
    }

    /**
     * Create an instance of {@link Ken21083KcbCustomerAccountCreateRequest }
     * 
     */
    public Ken21083KcbCustomerAccountCreateRequest createKen21083KcbCustomerAccountCreateRequest() {
        return new Ken21083KcbCustomerAccountCreateRequest();
    }

    /**
     * Create an instance of {@link Ken21083KcbCustomerAccountCreateResponse }
     * 
     */
    public Ken21083KcbCustomerAccountCreateResponse createKen21083KcbCustomerAccountCreateResponse() {
        return new Ken21083KcbCustomerAccountCreateResponse();
    }

}
